import json
import logging
import os
import re
import sys
import time
import uuid
from pathlib import Path

import pandas as pd
from tqdm import tqdm

#  Importar desde shared
sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
from src.shared.constants import (
    DATA_CORPUS_DIR,
    DEVGPT_DATA_PATH,
    EXTENSION_MAP,
    GITHUB_TOKEN,
    METADATA_CSV,
    METADATA_DIR,
    VALID_LANGUAGES,
)

#  Logging 
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [FASE-1] %(levelname)s — %(message)s",
    datefmt="%H:%M:%S",
)
log = logging.getLogger(__name__)

# Constantes internas 
MIN_CODE_LENGTH = 50   # descartar fragmentos triviales 

# Mapa de alias de tipo DevGPT → lenguaje canónico del pipeline
LANG_ALIASES: dict[str, str] = {
    "python": "python",
    "py":     "python",
    "c":      "c",
    "cpp":    "cpp",
    "c++":    "cpp",
    "cxx":    "cpp",
    "cc":     "cpp",
}

# Queries de GitHub para búsqueda de código IA
GITHUB_QUERIES = [
    # GitHub Copilot (Integrados en el IDE)
    "copilot generated",
    "co-authored-by: GitHub Copilot",
    
    # Familia OpenAI (ChatGPT)
    # "generated by chatgpt",
    # "written by chatgpt",
    # "generated by gpt-4",
    # "generated by gpt-3.5",
    # 
    # Familia Anthropic (Claude)
    # "generated by claude",
    # "written by claude",
    
    # Familia Google (Gemini / Bard)
    # "generated by gemini",
    # "generated by bard",
    
    # Familia DeepSeek (Muy popular en código actualmente)
    # "generated by deepseek",
    # "written by deepseek",
    
    # Términos Genéricos
    "generated by AI",
    "AI generated code"
]
GITHUB_MAX_RESULTS = 100  # por query

#  Helpers 

def _normalize_language(raw_type: str) -> str | None:
    return LANG_ALIASES.get(raw_type.strip().lower())


def _make_record(
    file_id: str,
    language: str,
    source_type: str,
    source_url: str,
    original_prompt: str,
) -> dict:
    ext = EXTENSION_MAP[language]
    return {
        "file_id":          file_id,
        "filename":         f"{file_id}{ext}",
        "language":         language,
        "source_type":      source_type,
        "source_url":       source_url,
        "original_prompt":  original_prompt[:500],
        "perplexity_score": -1.0,
        "is_ai_generated":  "",
        "vulnerability_ids":"",
        "cvss_max":         -1.0,
        "patch_status":     "pending",
        "iterations_used":  0,
        "final_cvss":       -1.0,
    }


def _save_code_file(content: str, language: str) -> str:
    """
    Guarda el bloque de código en data/corpus/{uuid}{ext}.
    Retorna el file_id (UUID puro, sin extensión).
    """
    file_id = str(uuid.uuid4())
    ext = EXTENSION_MAP[language]
    dest = os.path.join(DATA_CORPUS_DIR, f"{file_id}{ext}")
    with open(dest, "w", encoding="utf-8") as f:
        f.write(content)
    return file_id


# Fuente 1: DevGPT 

def _extract_from_devgpt(json_path: str) -> list[dict]:
    """
    Parsea un snapshot DevGPT y retorna lista de registros de metadata.
    Estructura real del JSON:
      {"Sources": [ {... "ChatgptSharing": [ {"Conversations": [...]} ]} ]}
    """
    records: list[dict] = []

    log.info("Cargando snapshot: %s", os.path.basename(json_path))
    with open(json_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    sources = data.get("Sources", [])
    log.info("  → %d fuentes encontradas", len(sources))

    for source_item in tqdm(sources, desc=f"  {os.path.basename(json_path)}", leave=False):
        sharings = source_item.get("ChatgptSharing", [])
        if not sharings:
            continue

        for share in sharings:
            share_url = share.get("URL", "")
            conversations = share.get("Conversations", [])

            for turn_idx, conv in enumerate(conversations):
                prompt_text = conv.get("Prompt", "")
                code_blocks = conv.get("ListOfCode", [])

                if not code_blocks:
                    # Intentar extraer bloques markdown del campo Answer
                    answer_text = conv.get("Answer", "")
                    if answer_text:
                        code_blocks = [
                            {"Type": lang, "Content": code}
                            for lang, code in _extract_markdown_blocks(answer_text)
                        ]

                for code_block in code_blocks:
                    raw_type = str(code_block.get("Type", "")).lower()
                    content  = code_block.get("Content", "")

                    language = _normalize_language(raw_type)
                    if language is None:
                        continue 
                    if not content or len(content.strip()) < MIN_CODE_LENGTH:
                        continue 

                    file_id = _save_code_file(content.strip(), language)
                    records.append(
                        _make_record(
                            file_id=file_id,
                            language=language,
                            source_type="devgpt",
                            source_url=share_url,
                            original_prompt=prompt_text,
                        )
                    )

    log.info("  → %d archivos extraídos de %s", len(records), os.path.basename(json_path))
    return records


def _extract_markdown_blocks(text: str) -> list[tuple[str, str]]:
    """Extrae bloques de código markdown del campo Answer como fallback."""
    patron = r"```(\w*)\n(.*?)```"
    matches = re.findall(patron, text, re.DOTALL)
    return [(lang.lower() or "unknown", code.strip()) for lang, code in matches]


#  Fuente 2: GitHub API 

def _extract_from_github(max_results: int = GITHUB_MAX_RESULTS) -> list[dict]:
    """
    Busca commits con keywords de generación IA en GitHub y descarga archivos .py/.c/.cpp.
    Requiere GITHUB_TOKEN en .env.
    """
    if not GITHUB_TOKEN:
        log.warning("GITHUB_TOKEN no configurado — omitiendo fuente GitHub.")
        return []

    try:
        from github import Github
        from github.GithubException import RateLimitExceededException, UnknownObjectException
    except ImportError:
        log.error("PyGithub no instalado. Ejecuta: pip install PyGithub")
        return []

    records: list[dict] = []
    g = Github(GITHUB_TOKEN)

    VALID_EXT_MAP = {".py": "python", ".c": "c", ".cpp": "cpp", ".cxx": "cpp", ".cc": "cpp"}

    for query in GITHUB_QUERIES:
        log.info("GitHub query: %s", query)
        try:
            commits = g.search_commits(query=query, sort="committer-date", order="desc")
            count = 0

            for commit in commits:
                if count >= max_results:
                    break
                try:
                    repo = commit.repository
                    files = commit.files
                    for f in files:
                        if count >= max_results:
                            break
                        filename_lower = (f.filename or "").lower()
                        ext = os.path.splitext(filename_lower)[1]
                        language = VALID_EXT_MAP.get(ext)
                        if language is None:
                            continue

                        # Obtener contenido raw
                        try:
                            raw_content = repo.get_contents(f.filename, ref=commit.sha)
                            if isinstance(raw_content, list):
                                continue
                            code = raw_content.decoded_content.decode("utf-8", errors="replace")
                        except (UnknownObjectException, Exception):
                            continue

                        if len(code.strip()) < MIN_CODE_LENGTH:
                            continue

                        file_id = _save_code_file(code.strip(), language)
                        records.append(
                            _make_record(
                                file_id=file_id,
                                language=language,
                                source_type="github",
                                source_url=f.blob_url or repo.html_url,
                                original_prompt=commit.commit.message[:500] if commit.commit.message else "",
                            )
                        )
                        count += 1

                except RateLimitExceededException:
                    log.warning("Rate limit de GitHub alcanzado. Esperando 60s...")
                    time.sleep(60)
                except Exception as e:
                    log.debug("Error procesando commit: %s", e)
                    continue

        except RateLimitExceededException:
            log.warning("Rate limit de GitHub. Saltando query '%s'.", query)
        except Exception as e:
            log.error("Error en búsqueda GitHub '%s': %s", query, e)

    log.info("GitHub → %d archivos extraídos.", len(records))
    return records


#  Función principal de la fase 

def run_phase1(skip_github: bool = False) -> int:
    """
    Construye el corpus de código fuente desde DevGPT y GitHub.

    Args:
        skip_github: Si True, omite la fuente GitHub 

    Returns:
        Número de registros creados en registro_metadatos.csv.
    """
    #  Crear directorios si no existen 
    os.makedirs(DATA_CORPUS_DIR, exist_ok=True)
    os.makedirs(METADATA_DIR, exist_ok=True)

    all_records: list[dict] = []

    #  Fuente 1: DevGPT 
    devgpt_path = Path(DEVGPT_DATA_PATH)
    if not devgpt_path.exists():
        log.error("DEVGPT_DATA_PATH no existe: %s", devgpt_path)
    else:
        json_files = sorted(devgpt_path.glob("*.json"))
        if not json_files:
            log.warning("No se encontraron archivos .json en %s", devgpt_path)
        else:
            log.info("Procesando %d snapshots de DevGPT...", len(json_files))
            for json_file in json_files:
                try:
                    records = _extract_from_devgpt(str(json_file))
                    all_records.extend(records)
                except Exception as e:
                    log.error("Error procesando %s: %s", json_file.name, e)

    #  Fuente 2: GitHub API 
    if not skip_github:
        log.info("Extrayendo desde GitHub API...")
        github_records = _extract_from_github()
        all_records.extend(github_records)
    else:
        log.info("Fuente GitHub omitida (skip_github=True).")

    #  Persistir CSV 
    if not all_records:
        log.error("No se encontró código válido en ninguna fuente.")
        return 0

    # Si el CSV ya existe, añadir solo los nuevos (evitar duplicados por file_id)
    if os.path.exists(METADATA_CSV):
        df_existing = pd.read_csv(METADATA_CSV, dtype=str)
        existing_ids = set(df_existing["file_id"])
        new_records = [r for r in all_records if r["file_id"] not in existing_ids]
        if new_records:
            df_new = pd.DataFrame(new_records)
            df_combined = pd.concat([df_existing, df_new], ignore_index=True)
        else:
            df_combined = df_existing
            log.info("No hay nuevos registros para añadir.")
    else:
        df_combined = pd.DataFrame(all_records)

    df_combined.to_csv(METADATA_CSV, index=False, encoding="utf-8")

    total = len(df_combined)
    new_added = len(all_records)
    log.info("=" * 60)
    log.info("FASE 1 completada.")
    log.info("  Total en registro_metadatos.csv : %d", total)
    log.info("  Archivos nuevos esta ejecución  : %d", new_added)
    log.info("  Corpus guardado en              : %s", DATA_CORPUS_DIR)
    log.info("=" * 60)

    #  Verificar criterio de aceptación 
    if total < 50:
        log.warning(
            "Criterio de aceptación NO cumplido: se necesitan >=50 filas, hay %d.", total
        )
    else:
        log.info("✓ Criterio de aceptación CUMPLIDO (>=50 filas).")

    return total


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="Fase 1 — Corpus Builder")
    parser.add_argument(
        "--skip-github",
        action="store_true",
        help="Omite la extracción desde GitHub API (más rápido para pruebas).",
    )
    args = parser.parse_args()

    n = run_phase1(skip_github=args.skip_github)
    sys.exit(0 if n >= 50 else 1)
